### ISSUE TITLE
When will vaccine data for NYC be added to this repo?

### ISSUE THREAD

**Issue by rguttersohn** [nychealth/covid-vaccine-data#1]

**Comment by rguttersohn** [comment]
It looks like the city has data on vaccines administered, etc. When will it be added to this repo? Or is there another source for vaccines?

**Comment by Zorter** [comment]
Have same question - what to show vaccination results base on the date. https://www1.nyc.gov/site/doh/covid/covid-19-data-vaccines.page just has this day's data. I want data for every day for the last month. Thank you.

**Comment by bertrandmartel** [comment]
@Zorter @rguttersohn I've just made this repository https://github.com/bertrandmartel/covid19-nyc-vaccine-tracker which scrapes data from Tableau using [this library](https://github.com/bertrandmartel/tableau-scraping). It runs daily using Github actions

**Comment by Zorter** [comment]
Marcel

I had found the Tableau representation. They keep changing it. The 
description are not easy to understand - especially their use of % 
percentages. Percentages of what.

I also am not impressed that one cannot go back in time, as one example. 
Maybe it is possible, but, if so, not explained.

Tableau is really a narrow slice - NYC could do a lot better. Make is 
easy to download more of the data.

I will look at the github documentation later this week.

I guess it is better than Florida.

Thank you for info.

Alan

On 03/22/2021 07:07, Bertrand Martel wrote:

> @Zorter [1] @rguttersohn [2] I've just made this repository 
> https://github.com/bertrandmartel/covid19-nyc-vaccine-tracker which 
> scrapes data from Tableau using this library [3]. It performs daily 
> using Github actions
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [4], or unsubscribe 
> [5].


Links:
------
[1] https://github.com/Zorter
[2] https://github.com/rguttersohn
[3] https://github.com/bertrandmartel/tableau-scraping
[4] 
https://github.com/nychealth/covid-vaccine-data/issues/1#issuecomment-803977933
[5]

**Comment by Zorter** [comment]
Sorry. I see you are pulling data from the Tableau version. Nice hack.

On 03/22/2021 07:07, Bertrand Martel wrote:

> @Zorter [1] @rguttersohn [2] I've just made this repository 
> https://github.com/bertrandmartel/covid19-nyc-vaccine-tracker which 
> scrapes data from Tableau using this library [3]. It performs daily 
> using Github actions
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [4], or unsubscribe 
> [5].


Links:
------
[1] https://github.com/Zorter
[2] https://github.com/rguttersohn
[3] https://github.com/bertrandmartel/tableau-scraping
[4] 
https://github.com/nychealth/covid-vaccine-data/issues/1#issuecomment-803977933
[5]

**Comment by rguttersohn** [comment]
Yes! Great work. Is this app sitting on a server somewhere are you able to simply post this on Github and it conducts the actions daily?

**Comment by bertrandmartel** [comment]
@rguttersohn it's just using Github actions with the following configuration https://github.com/bertrandmartel/covid19-nyc-vaccine-tracker/blob/master/.github/workflows/report.yaml . No server is needed, the job is scheduled [everyday](https://github.com/bertrandmartel/covid19-nyc-vaccine-tracker/blob/master/.github/workflows/report.yaml#L4) and commit to the `master` branch
