### ISSUE TITLE
Coverage-by-Demo-AllAges

### ISSUE THREAD

**Issue by warrtalon** [nychealth/covid-vaccine-data#10]
Hello, @acharney2, I am tagging you because I'm unable to tag ebubakar and cchang21 (the last 2 to commit data on this file).

For weeks 1/1 and 1/8, the Vax and Unvax numbers for Cases seem highly skewed compared to prior weeks. Is this data correct, or were there tens of thousands of cases not yet categorized and thus left within unvaxxed?

I ask because the rate of change is drastic. The data indicate vaxxed cases went down during the height of the City's incline, and the rate between Vax and Unvax dropped off a cliff. 

In weeks 12/18 and 12/25, more than half the cases were vaxxed, but then weeks of 1/1 and 1/8 show a drastic falloff that does not make sense.

I'm hoping to find out if these are data integrity errors or if the data just hasn't been categorized yet due to unknown vax status.

Btw, this drastic difference in cases seems to filter into Hospitalizations, too (and likely Deaths), so it's important to get this fixed throughout.
![NYCHealth_Cases_2022-01-21](https://user-images.githubusercontent.com/98188224/150599847-63986671-f7f2-42ea-bd44-8c76587e4a45.png)

Thank you!
Clayton

**Comment by acharney2** [comment]
Hi Clayton, Thank you for reaching-out.

Recent data starting from 12/25 may be incomplete due to delays in processing the substantial surge in cases and linking to vaccination and hospitalization data. As data backfills over time, this will be corrected. Sharing the figure from our website for reference. 

![Screen Shot 2022-01-21 at 1 16 23 PM](https://user-images.githubusercontent.com/77995104/150604076-61534057-f3ef-41f2-a630-2d9550b8c611.png)

**Comment by warrtalon** [comment]
> 

Ariel, thank you kindly. This is what I suspected, and I had noticed the gray shading with the warning. However, do the adjustments only go one direction? Do all assignments start as Unvaxxed until they get moved into Vaxxed?

I noticed the 12/25 data significantly shifted from Unvaxxed to Vaxxed after already being weighted more evenly than 1/1 and 1/8.

12/25 (8 days ago):
- Vaxxed Cases: 73,698
- Unvaxxed Cases: 82,003

12/25 (1 day ago):
- Vaxxed Cases: 88,014 (+14,316)
- Unvaxxed Cases: 65,266 (-16,737)

Vaxxed went from 46% of Cases to 56%.

Do we expect the same for 1/1 and 1/8? Do you know why so many move from Unvaxxed to Vaxxed? Is Unvaxxed inclusive of both Unvaxxed Confirmed and Unknown? Do all Unknowns go in the Unvax bucket?

Sorry for all the questions - I am not sure where else to go, so that's why I submitted an Issue.

Thank you!

**Comment by acharney2** [comment]
No problem! Hope this clears-up some more of your questions: 

The changes week-by-week are due to lags in the data coming in. The data is dynamic and backfills with cases that have been newly matched to vaccination records. Cases that don’t match to a vaccination record are classified as unvaccinated, including “unknowns”. The data for 12/25 might have backfilled more than usual because of the recent addition of the 5-11 year olds.

**Comment by warrtalon** [comment]
Ariel, thank you so much. I could probably ask 1,000 questions, but I don't want to burn your good will. Please let me know if there is a better way to ask questions or a better person to bother. So far, you've been super helpful, thank you!

The response about Unvaxxed and Unknowns is critically important - thanks so much.

Is it possible to keep Unknowns in its own Bucket until investigation is complete? How is Unvaxxed verified, or do Unvaxxed only mean there was no Vax record found? Meaning...is Unvaxxed just everything left after finding Vax matches, or is Unvaxxed status verified before counted as Unvaxxed?

Do the vax classifications get updated regularly or only once each Thursday? I see commits occur regularly but don't know if that type of data update occurs more than once per week.

Warm Regards.

**Comment by warrtalon** [comment]
12/25 (9 days ago):
- Vaxxed Hosps: 1398
- Unvaxxed Hosps: 1799

12/25 (2 days ago):
- Vaxxed Hosps: 1474 (+76)
- Unvaxxed Hosps: 1744 (-55)

Net shift to Vaxxed = 131
Vaxxed % of Total Hosps increased from 43.7% to 45.8%
---------------------------------------------------------
12/25 (9 days ago):
- Vaxxed Deaths: 65
- Unvaxxed Deaths: 113

12/25 (2 days ago):
- Vaxxed Deaths: 93 (+17)
- Unvaxxed Deaths: 154 (+41)

Vaxxed % of Total Hosps increased from 36.5% to 37.7%

**Comment by acharney2** [comment]
"Unvaccinated" refers to people age 5 and over with no record of vaccination status. New cases are matched weekly and then we rematch cases four weeks after they were sent for the initial match, thus data will backfill from previous weeks. Data on cases/hosp/deaths by vaccination status are updated weekly on Thursdays. 

Thanks, Ariel
