### ISSUE TITLE
Vaccination Rates exceeding 100%

### ISSUE THREAD

**Issue by warrtalon** [nychealth/covid-vaccine-data#11]
Hello, Jackson @NYC-DOHMH-JB , it seems the vaccination rates posted in covid-vaccine-data/people/coverage-by-demo.csv are increasingly becoming invalid as more and more demographics exceed 100%.

I know the Readme says this is possible for race/ethnicity in small groupings due to some people possibly being counted in both, but it is now happening in the age groupings. Also, it happened in the Asian grouping, which is over 1M total people. It's not possible for over 100% of Asians/HNPI to be vaccinated nor for over 100% of 18-24.

This means the population numbers are wrong. If the population numbers are wrong, then the unvaccinated calculations are also wrong. This throws all the comparisons off dramatically.

Can the population numbers be fixed?
![image](https://user-images.githubusercontent.com/98188224/151059417-9532d574-3a30-4a4f-ae67-a60b7a7d8870.png)
![image](https://user-images.githubusercontent.com/98188224/151059435-29e229da-7ebc-4614-ba14-12627ff826d8.png)

Thank you!
Clayton

**Comment by acharney2** [comment]
Hi Clayton, There are a number of reasons for this which are documented in our readme. Copying here: 

The number of people vaccinated may exceed the estimated population and lead to more than 100% vaccination coverage, especially for smaller demographic categories and geographies. These estimates do not represent the 2020 Census or recent changes to NYC’s population as a result of in-migration or out-migration. Additional factors contributing to these inconsistencies may be that people who identify as Multi-race are misreported under a single race, and self-reported ZIP code at the time of vaccination may not correspond to the vaccine recipient’s primary home address. For example, people may use their work address for the purposes of vaccination.

The population estimates for the 2020 census across various stratifications are currently being finalized.

**Comment by warrtalon** [comment]
Thank you, Ariel. I saw in the readme, but that explanation can't account for the age groups exceeding 100%. Also, it mentions "smaller demographic categories," but we're seeing over 100% in very large categories (18-24 and Asian/HNPI).

When you mention the 2020 pop estimates are being finalized, do you mean the whole system will be updated with those denominators once they are finalized (replacing the much lower 2019 estimates)? Is this something happening in days, weeks, or months (assuming you know and are able to share)?

Thanks a mil.

**Comment by acharney2** [comment]
We are actively working on updating the population estimates and will notify users once the adjustment is made. The 2020 Census showed that NYC's population grew substantially and we're waiting on the breakdowns by race and age for different geographies. Thank you for your patience!

**Comment by warrtalon** [comment]
Superb, thank you. That answers my question on this Issue for now.

Thanks again,
Clayton
