### ISSUE TITLE
Population Estimates (2019 vs. 2023)

### ISSUE THREAD

**Issue by warrtalon** [nychealth/covid-vaccine-data#14]
Hello again, @acharney2 

I wanted to rekindle this topic from one year ago (Feb 2022): https://github.com/nychealth/covid-vaccine-data/issues/12#issuecomment-1041880861.

It seems nycHealthy is still using the 2019 intercensal for Vax vs. Unvax denominators, and these numbers have gotten so out of hand that we are now down to 3,405 total Unvaccinated adults (18+) in NYC. We of course know this isn't true, but the public has no idea that such egregiously wrong population denominators are driving the NYC DOH Vax vs. Unvax charts.

These artificially-low denominators lead to artificially large - and inaccurate - gaps between Vax and Unvax age-adjusted rates.

This then leads to negative downstream policy outcomes like:
- Unvaccinated NYC parents not being allowed to step foot on school grounds due to the DOH Commissioner not knowing the CoV2 Unvax rates are completely wrong
- The White House basing policy decisions off the CDC’s inflated Vax vs. Unvax Incident Rate Ratios (IRR) due in part to NYC supplying false numbers as one of the 23 participating jurisdictions

Can nycHealthy at least change the Population Vax%, Unvax rates, and all age-adjusted rates to reflect the 2020 census?

Maintaining these egregiously false numbers ONLY for ease of comparison is wholly inappropriate. I think you and the NYC public would agree.

Thank you kindly,
Clayton
![image](https://user-images.githubusercontent.com/98188224/217568048-25ce7271-409e-425e-b2a6-889a47eea572.png)
![image](https://user-images.githubusercontent.com/98188224/217568113-d1df7037-70ab-4850-99fc-bc999fb3f8a6.png)

**Comment by mmueller1-NYCDOHMH** [comment]
Hi @warrtalon,

Apologies for the delayed response. We are aware of the issues presented with using the old census numbers but we are still waiting for final 2020 Census data. Once we have that we will get the new estimates up asap.
