### ISSUE TITLE
Need weekly data from Jan-March '21 (by zip) of Covid-19 Vaccination Rates

### ISSUE THREAD

**Issue by ngryczka** [nychealth/covid-vaccine-data#2]
Hello, 

My name is Natalia and I am a project manager for Maimonides Hospital Psychiatry department. My team and I are writing a research paper about the Brooklyn Rates surrounding Maimonides Hospital. We have found weekly data from April through now, and were wondering if there is any weekly data from January - March 2021?

**Comment by acharney2** [comment]
Hi Natalia, 

Thank you for the question. Data from that period was not publicly available yet. Please submit a data request to idt@health.nyc.gov and we can try to assist. 

Thank you, Ariel

**Comment by ngryczka** [comment]
Thank you so much for responding! I will absolutely submit a data request.
