### ISSUE TITLE
Financial District reporting >100% partially vaccinated

### ISSUE THREAD

**Issue by davidnir** [nychealth/covid-vaccine-data#3]
When selecting the "fully vaccinated" radio button on this map, the Financial District shows >100% of the population that's received at least one dose: https://www1.nyc.gov/site/doh/covid/covid-19-data-vaccines.page#byzip

<img width="320" alt="Screen Shot 2021-06-07 at 12 55 33 PM" src="https://user-images.githubusercontent.com/14263427/121060182-4f9f7380-c790-11eb-8293-f9730b0eff35.png">

**Comment by acharney2** [comment]
Thank you for your question! Please refer to our documentation below for an explanation of why certain areas have coverage numbers above 100%: https://github.com/nychealth/covid-vaccine-data#zip-codes-and-zip-code-tabulation-areas-zctas

_The number of people vaccinated in some neighborhoods may exceed the estimated population. The percentage of people vaccinated are calculated using intercensal population estimates from 2019, which do not reflect the most recent 2020 Census numbers. Additional factors contributing to these inconsistencies may be that self-reported ZIP code at the time of vaccination may not correspond to the vaccine recipient’s primary home address. For example, people may use their work address for the purposes of vaccination._
