### ISSUE TITLE
10018

### ISSUE THREAD

**Issue by HarryLeroy** [nychealth/covid-vaccine-data#4]
The 10018 zip code numbers appear to be off, with almost 120% of the total population listed as having received a dose. Moreover, the numbers are also far and away the fastest growing in all of New York City--the rate of weekly increase is more than twice that of the next highest zip code (10036, also in Chelsea). I know the population denominators aren't going to be perfect for any zip code, but is there another reason for this aberration?

Thanks,
HL

**Comment by acharney2** [comment]
Thank you for your question! Please refer to our documentation below for an explanation of why certain areas have coverage numbers above 100%: https://github.com/nychealth/covid-vaccine-data#zip-codes-and-zip-code-tabulation-areas-zctas

_The number of people vaccinated in some neighborhoods may exceed the estimated population. The percentage of people vaccinated are calculated using intercensal population estimates from 2019, which do not reflect the most recent 2020 Census numbers. Additional factors contributing to these inconsistencies may be that self-reported ZIP code at the time of vaccination may not correspond to the vaccine recipient’s primary home address. For example, people may use their work address for the purposes of vaccination._
