### ISSUE TITLE
Booster Shots

### ISSUE THREAD

**Issue by HarryLeroy** [nychealth/covid-vaccine-data#6]
How is the city presently accounting for (or planning to account for) booster shots?

Thanks,
HL

**Comment by acharney2** [comment]
Hi HL, 

Boosters/Dose 3 are not accounted for but will be added soon. We are awaiting further guidance from the Advisory Committee on Immunization Practices (ACIP) after which we will integrate the data in our regular updates. 

Thank you, 
Ariel
