### ISSUE TITLE
Reporting on Vaccinations for 5-11

### ISSUE THREAD

**Issue by HarryLeroy** [nychealth/covid-vaccine-data#7]
When are kids' vaccination numbers going to show up in the data? It's been over a week since the vaccine was approved for children 5 and over, and it doesn't look like most of those jabs have gotten picked up in the reporting.

Thanks,
HL

**Comment by acharney2** [comment]
Hi HL, We are currently working on adding these data and they should be up soon. Thank you for your patience!

**Comment by acharney2** [comment]
Data on 5-11 is now posted! Best, Ariel
