### ISSUE TITLE
Data does not seem to be getting updated for Zip Code 10024

### ISSUE THREAD

**Issue by benjobes** [nychealth/covid-vaccine-data#8]
I check the map daily for my zip code...10024. Since you represent the percentages out to 2 points, I could always count on at least some movement every day. Then one day a few weeks ago, it stopped at 79.24 with at least one dose and 74.43 fully vaccinated and has stayed there ever since. While actual vaccination my have slowed, I doubt it suddenly ground to a halt in one day. What's going on?

**Comment by acharney2** [comment]
Hi Ben, Looks like the data is updating properly on [Github](https://github.com/nychealth/covid-vaccine-data/blob/main/people/coverage-by-modzcta-allages.csv), but the figure was not refreshing properly on our website. This should be fixed momentarily. The data for 10024 currently shows 80.97 (at least 1 dose) and 75.37 (fully vaccinated). Thank you for the flag!
